CONTIKI_PROJECT = normal-node attacker-node sdn-controller
all: $(CONTIKI_PROJECT)

# Update path to match your system
CONTIKI = /home/stalin/655project/contiki-ng

# Network stack configuration
MAKE_MAC = MAKE_MAC_CSMA
MAKE_ROUTING = MAKE_ROUTING_RPL_LITE
MAKE_NET = MAKE_NET_IPV6

# Remove debug flags that might conflict
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
